### ISSUE TITLE
Why don't I see the HTML Notes?

### ISSUE THREAD

**Issue by kristineds** [websharks/comet-cache-kb#110]
---
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Why don't I see the HTML Notes?
categories: questions
tags: 
author: 
github-issue: https://github.com/websharks/comment-mail-kb/issues/#
```
---
_[We need to write an article that explains why the HTML notes are not displayed for site owners when they are using CloudFlare. See also [private, internal ticket](https://websharks.zendesk.com/agent/tickets/11077)]_
