### ISSUE TITLE
Why are Query Strings being cached when GET Request Caching is disabled?

### ISSUE THREAD

**Issue by raamdev** [websharks/comet-cache-kb#3]
---
##### KB Article Creation Checklist
- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

``` yaml
title: Why are Query Strings being cached when GET Request Caching is disabled?
categories: questions
tags: 
author: raamdev
github-issue: https://github.com/websharks/zencache-kb/issues/3
```

---

This KB article should point to [Nginx Configuration: `try_files` statement](https://github.com/websharks/zencache-kb/issues/2) and possibly provide some steps for testing if Nginx is not being used. See Jason's comments on https://github.com/websharks/quick-cache/issues/216 for examples.
