### ISSUE TITLE
How does the HTML Compressor locate JS/CSS for compression?

### ISSUE THREAD

**Issue by raamdev** [websharks/comet-cache-kb#54]
---
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: How does the HTML Compressor locate JS/CSS for compression?
categories: questions
tags: html-compression
author: raamdev
github-issue: https://github.com/websharks/zencache-kb/issues/54
```
---
The HTML Compressor looks at the output of the raw HTML and searches for any JavaScript and CSS files that may be included on the page, along with any inline snippets. In other words, the HTML Compressor does a very good job of detecting and concatenating JS/CSS.
